language: python
cache:
  - pip
  -
python:
  - "3.7"

node_js:
  - "10"

env: TOXENV=py37-codecov
dist: xenial

install:
  - npm install
  - pip install tox

script:
  - tox

services:
  - postgresql
