language: minimal  # https://docs.travis-ci.com/user/languages/minimal-and-generic/
dist: xenial  # https://docs.travis-ci.com/user/reference/xenial/

# Default to skipping install and script steps if not overridden in jobs.
install: skip
script: skip

jobs:
  include:

    - stage: test
      name: "Tox"
      language: python
      python: 3.7
      env: TOXENV=py37-codecov
      services:
        - postgresql
      install:
        - pip install tox
      script:
        - tox

    - stage: test
      name: "docker-compose build"
      services:
        - docker
      script:
        # TODO: --cache-from
        - docker-compose -f deploy/docker-compose.yml build
        - docker images

    # Deploy if successful.

    - stage: deploy
      name: "docker-compose push"
      if: branch = deploy-test
      services:
        - docker
      script:
        # TODO: --cache-from
        - docker-compose -f deploy/docker-compose.yml build
        - docker images

        # Credentials at https://travis-ci.com/OpenUpSA/khetha-django/settings
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        - docker-compose -f deploy/docker-compose.yml push;
