language: python
cache: pip

matrix:
  include:
    # Python 3.7 requires "dist: xenial", for now.
    # See:
    # https://docs.travis-ci.com/user/languages/python/#specifying-python-versions
    - { python: '3.7', env: TOXENV=py37-codecov, dist: xenial }

install:
  - pip install tox

script:
  - tox

services:
  - postgresql
