# docker-compose for (local test) deployment
#
version: '3.4'


services:

  db:
    # Constrain PostgreSQL major version, for data compatibility.
    image: postgres:11-alpine
    volumes:
    - khetha-postgres-data-11:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile.deploy
      target: khetha-django-gunicorn
    environment:
    - DJANGO_ALLOWED_HOSTS=127.0.0.1
    - DJANGO_DATABASE_URL=postgres://postgres@db/postgres?atomic_requests=True
    - DJANGO_SECRET_KEY=khetha-docker-FIXME

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.deploy
      target: khetha-nginx
    ports:
    - 8000:80


volumes:
  khetha-postgres-data-11:
