# Generated by Django 2.1.7 on 2019-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("khetha", "0002_schema_sketch")]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption", options={"ordering": ["order"]}
        ),
        migrations.AlterModelOptions(name="question", options={"ordering": ["order"]}),
        migrations.AlterModelOptions(name="task", options={"ordering": ["order"]}),
        migrations.AddField(
            model_name="answeroption",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
