# Generated by Django 2.1.7 on 2019-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("khetha", "0004_add_submissions")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="display_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Short text"),
                    (2, "Long text"),
                    (3, "Buttons"),
                    (4, "Select list"),
                ],
                db_index=True,
                default=1,
            ),
        )
    ]
