# Generated by Django 2.1.7 on 2019-04-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("khetha", "0005_question_display_type")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Short text"),
                    (11, "Long text"),
                    (12, "Place field"),
                    (20, "Buttons"),
                    (30, "Select list"),
                    (40, "Radio buttons"),
                ],
                db_index=True,
                default=10,
            ),
        )
    ]
