# Base docker-compose.yml for deployment.
#
version: '3.4'


services:

  db:
    # Constrain PostgreSQL major version, for data compatibility.
    image: postgres:11-alpine
    volumes:
    - khetha-postgres-data-11:/var/lib/postgresql/data

  django:
    image: pjdelport/khetha-django
    build:
      context: ..
      dockerfile: Dockerfile.deploy
      target: khetha-django-gunicorn
    environment:
    - DJANGO_DATABASE_URL=postgres://postgres@db/postgres

  nginx:
    image: pjdelport/khetha-nginx
    build:
      context: ..
      dockerfile: Dockerfile.deploy
      target: khetha-nginx


volumes:
  khetha-postgres-data-11:
